[package]
name = "signature-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "^2.0.12"
num-rational = "^0.4.2"
num-integer = "^0.1.46"
bitvec = "^1.0.1"
indicatif = {version = "^0.18.0", optional = true}

[dev-dependencies]
rstest = "^0.25.0"

[features]
default = []
progress = ["indicatif"]

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
