[package]
name = "signature-py"
version = "0.2.0"
edition = "2024"
license = "AGPL-3.0-only"
description = "High-performance log signature computation for paths and time series data"
documentation = "https://docs.rs/signature-rs"
homepage = "https://github.com/ChosunOne/signature-rs"
repository = "https://github.com/ChosunOne/signature-rs"
readme = "README.md"
keywords = ["log", "signature", "lie", "paths", "series"]
categories = ["data-structures", "mathematics", "science", "algorithms"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "signature_py"
crate-type = ["cdylib"]

[dependencies]
numpy = "^0.25.0"
ndarray = "^0.16.1"
ordered-float = "^5.0.0"
pyo3 = {version = "^0.25.1", features = ["ordered-float"] }
lyndon-rs = {path = "../lyndon-rs", version = "0.2.0"}
commutator-rs = {path = "../commutator-rs", version = "0.2.0"}
lie-rs = {path = "../lie-rs", version = "0.2.0"}
signature-rs = {path = "../signature-rs", version = "0.2.0"}
