[package]
name = "commutator-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
lyndon-rs = {path = "../lyndon-rs"}
ordered-float = "^5.0.0"
num-traits = "^0.2.19"

[dev-dependencies]
rstest = "^0.26.1"
