[package]
name = "commutator-rs"
version = "0.1.0"
edition = "2024"
license = "AGPL-3.0-only"

[dependencies]
lyndon-rs = {path = "../lyndon-rs"}
num-traits = "^0.2.19"

[dev-dependencies]
rstest = "^0.26.1"
