[package]
name = "lyndon-py"
version = "0.2.0"
edition = "2024"
license = "AGPL-3.0-only"
description = "Lyndon words and Lyndon basis for free Lie algebras"
documentation = "https://docs.rs/lyndon-rs"
homepage = "https://github.com/ChosunOne/signature-rs"
repository = "https://github.com/ChosunOne/signature-rs"
readme = "README.md"
keywords = ["lyndon", "lie", "combinatorics", "free", "algebra"]
categories = ["data-structures", "mathematics", "science", "algorithms"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "lyndon_py"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "^0.25.1"
lyndon-rs = {path = "../lyndon-rs", version = "0.2.0"}
