[package]
name = "lyndon-py"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "lyndon_py"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "^0.25.1"
lyndon-rs = {path = "../lyndon-rs", version = "0.1.0"}
