[package]
name = "lie-rs"
version = "0.2.0"
authors = ["ChosunOne"]
edition = "2024"
license = "AGPL-3.0-only"
description = "Lie series and Baker-Campbell-Hausdorff formula computations"
documentation = "https://docs.rs/lie-rs"
homepage = "https://github.com/ChosunOne/signature-rs"
repository = "https://github.com/ChosunOne/signature-rs"
readme = "README.md"
keywords = ["lie", "bch", "algebra", "series", "baker"]
categories = ["data-structures", "mathematics", "science", "algorithms"]

[dependencies]
commutator-rs = {path = "../commutator-rs", version = "0.2.0"}
lyndon-rs = {path = "../lyndon-rs", version = "0.2.0"}
num-traits = "^0.2.19"
ordered-float = "^5.5.0"
rayon = "^1.12.0"
indicatif = {version = "^0.18.6", optional = true}
tracing = {version = "^0.1", optional = true}

[target.'cfg(target_os = "linux")'.dependencies]
libc = "0.2.189"

[dev-dependencies]
rstest = "^0.26.1"
num-rational = "^0.4.2"
ordered-float = "^5.5.0"
tracing-test = "^0.2"
tracing = "^0.1"
tracing-subscriber = { version = "^0.3.23", features = ["env-filter"] }
criterion = { version = "^0.8.2", features = ["html_reports"]}

[[bench]]
name = "commutation"
harness = false

[features]
default = []
progress = ["indicatif"]
tracing = ["dep:tracing", "commutator-rs/tracing"]
